### ISSUE TITLE
Create observability artifacts based on YAML configurations

### ISSUE THREAD

**Issue by minherz** [GoogleCloudPlatform/cloud-ops-sandbox#1026]
### Description

Today the properties of all observability artifacts are hardcoded in the Terraform files (see [provisioning/terraform/monitoring][1]). It means that every time we want to create another artifact (e.g. a SLO), we need to copy/paste the resource configuration. An attempt to avoid this kind of repetition was made with the monitoring dashboard artifacts. The configuration of multiple dashboards are stored in [provisioning/configurations/online-boutique/dashboards][2].

It would be useful to generalize this approach so it can be used for the all artifact types that Sandbox provisions. The current list of the artifacts includes:

* Monitoring dashboards
* Alerts
* Uptime checks
* Notification channels
* Log-based metrics
* SLOs

Additionally, the support for [custom monitored microservices][3] can be added as well.

[1]: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/tree/release/0.9/provisioning/terraform/monitoring
[2]: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/tree/release/0.9/provisioning/configurations/online-boutique/dashboards
[3]: https://cloud.google.com/stackdriver/docs/solutions/slo-monitoring/ui/define-svc

**Comment by minherz** [comment]
Among three possible forms of storing configurations (per demo application): single file; single folder; index file + referenced files, the **single folder** is selected.

_Single file_ form will have too many lines making it hard to manage.
_Index file + referenced files_ will require more complex implementation and extra maintenance.

Additionally, _single folder_ can be further enhanced to support as a single zip file making it easy for distributing

**Comment by minherz** [comment]
Additional validation for configuration should include:

* linting using yamllint
   ```terminal
   $ yamllint detection_rule.yml
   detection_rule.yml
     2:42      warning  too few spaces before comment  (comments)
     11:81     error    line too long (81 > 80 characters)  (line-length)
     15:81     error    line too long (102 > 80 characters)  (line-length)
   ```
* schema validation using Ansible's:
   ```yaml
   ---
   - hosts: localhost
     gather_facts: no
   
     vars:
       schema:
         type: object
         properties:
           name:
             type: string
           age:
             type: number
           email:
             type: string
             format: email
   
     tasks:
       - name: Load YAML file
         include_vars:
           file: data.yml
   
       - name: Validate YAML file
         assert:
           that:
             - "{{ data | from_yaml | json_query(schema) }}"
           success_msg: "YAML file is valid"
           fail_msg: "YAML file is invalid"
     ```

Both, yamllint and Ansible are installed on [Github hosted agents][link].

[link]: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools
